name: stream_builder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  decimal: ^3.2.1
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.4
  syncfusion_flutter_charts: ^29.1.39
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
